# Generated by Django 5.0.7 on 2024-08-06 18:57

import contact_book.contacts.validators
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Name must consist of at least 2 letters'), contact_book.contacts.validators.validate_contact_name])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='BG')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
