# Generated by Django 5.0.7 on 2024-08-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(default='Friends', on_delete=django.db.models.deletion.RESTRICT, to='contacts.category'),
            preserve_default=False,
        ),
    ]
